### ISSUE TITLE
sensitivity() not working in R 4.2.0

### ISSUE THREAD

**Issue by FridolinHaag** [manueleleonelli/bnmonitor#1]
I am using bnmonitor v0.1.3. With R <4.2.0 the diabetes example works flawlessly. 
```r
library("bnmonitor")
library("bnlearn")
library("qgraph")
library("gRain")
data(diabetes)
dag <- hc(diabetes)
bn <- bn.fit(dag , diabetes)
sens_dc <- sensitivity(bn , interest_node = "DIAB", interest_node_value = "pos", node = "GLUC", value_node = "high", value_parents = NULL , new_value = "all") 
#plot(sens_dc)
```
However, after an update to R 4.2.0, I receive an error:
```r
Error in if (!is.na(bnfit.new.scheme[[k]][[j]])) { : 
  the condition has length > 1
```
Could not really pin it down. Perhaps you have an idea.
Thanks a lot!

**Comment by manueleleonelli** [comment]
I'll have a look and let you know asap!

**Comment by manueleleonelli** [comment]
Hi updated the main folder on github. Do you want to try and download it from there and check?

**Comment by FridolinHaag** [comment]
Hi, I tried the latest version from github and it runs without error. I did not thoroughly test, but my results look reasonable. Thank you for addressing this so fast!
