### ISSUE TITLE
Naming Error in MutualInfo

### ISSUE THREAD

**Issue by vsocrates** [manueleleonelli/bnmonitor#2]
Amazing package! The only one that I've found that effectively calculates mutual information in a Bayesian network. Just a tiny bug with a column name in the mutual_info function: 

`MutalInfo` should be `MutualInfo`. 

https://github.com/manueleleonelli/bnmonitor/blob/9874ed1432d665d89149981ee063ed12ae187881/R/mutualinfo.R#L31

**Comment by manueleleonelli** [comment]
Hi Vimig, great that you found the package useful!!! And thanks for spotting the typo, I’ll fix it asap!

In the next release I will also add conditional MI, which I think could be useful.

**Comment by vsocrates** [comment]
Sounds great! A quick follow-up as I try to understand what these values mean (my stats knowledge is fairly limited), doesn't the MI itself already take into account conditional probabilities through marginalization of the CPT tables? 

I see MI as the relative information gain of one node on another, given the BN network structure. What kind of additional questions do you think we could answer with conditional MI?

**Comment by manueleleonelli** [comment]
You are correct that mutual information is computed using the model probabilities (and hence the CPTs). Mutual information is a measure of dependence between two variables. However one might be interested in the dependence between two variables conditional on a third. This would hence be a measure of conditional dependence. Check the wiki page https://en.m.wikipedia.org/wiki/Conditional_mutual_information

**Comment by vsocrates** [comment]
Ah yes, that makes perfect sense, thank you!
